---
- name: 'Add indexes to DB (I: "{{ instance.name }}", S: "{{ suffix.name }}", DB: "{{ db.name }}")'
  ldap_entry:
    bind_dn: '{{ dm_dn }}'
    bind_pw: '{{ dm_password }}'
    server_uri: '{{ server_uri }}'
    dn: 'cn={{ index.name }},cn=index,cn={{ db.name }},cn=ldbm database,cn=plugins,cn=config'
    objectClass:
      - top
      - nsIndex
    attributes:
      cn: '{{ index.name }}'
      nsSystemIndex: false
      nsIndexType: '{{ index.type }}'
  loop: '{{ db.index }}'
  loop_control:
    loop_var: index
  when: db.index is defined
  register: result

- name: 'Stop dirsrv service (I: "{{ instance.name }}", S: "{{ suffix.name }}", DB: "{{ db.name }}")'
  ansible.builtin.service:
    name: 'dirsrv@{{ instance.name }}'
    state: stopped
  when: result.changed

- name: 'Calculate indices with dsctl db2index (I: "{{ instance.name }}", S: "{{ suffix.name }}", DB: "{{ db.name }}")'
  ansible.builtin.command: '/usr/sbin/dsctl {{ instance.name }} db2index {{ db.name }}'
  args:
    chdir: /var/tmp
  when: result.changed

- name: 'Start dirsrv service (I: "{{ instance.name }}", S: "{{ suffix.name }}", DB: "{{ db.name }}")'
  ansible.builtin.service:
    name: 'dirsrv@{{ instance.name }}'
    state: started
  when: result.changed


- name: 'Include VLV creation routine(s) (I: "{{ instance.name }}")'
  ansible.builtin.include_tasks: vlv.yml
  loop: '{{ db.vlv_index }}'
  loop_control:
    loop_var: vlv_index
  when: db.vlv_index is defined
  vars:
    vlv_prefix1: '{% if db.vlv_prefix is defined %}{{ db.vlv_prefix }}_{% endif %}'
    vlv_prefix2: '{% if db.vlv_prefix is defined %}{{ db.vlv_prefix }}.{% endif %}'
