---
- name: 'Add indexes to DB {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  community.general.ldap_entry:
    bind_dn: '{{ dm_dn }}'
    bind_pw: '{{ dm_password }}'
    server_uri: '{{ server_uri }}'
    dn: 'cn={{ index.name }},cn=index,cn={{ db.name }},cn=ldbm database,cn=plugins,cn=config'
    objectClass:
      - top
      - nsIndex
    attributes:
      cn: '{{ index.name }}'
      nsSystemIndex: false
      nsIndexType: '{{ index.type }}'
      nsMatchingRule: '{{ index.matchingrule | default(omit) }}'
  loop: '{{ db.index }}'
  loop_control:
    loop_var: index
  when: db.index is defined
  register: result

- name: 'Update indexes to DB {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  community.general.ldap_attrs:
    bind_dn: '{{ dm_dn }}'
    bind_pw: '{{ dm_password }}'
    server_uri: '{{ server_uri }}'
    dn: 'cn={{ index.name }},cn=index,cn={{ db.name }},cn=ldbm database,cn=plugins,cn=config'
    attributes:
      nsIndexType: '{{ index.type }}'
      nsMatchingRule: '{{ index.matchingrule | default(omit) }}'
    state: exact
  loop: '{{ db.index }}'
  loop_control:
    loop_var: index
  when: db.index is defined
  register: result2

- name: 'Apply instance configuration in cn=changelog,{{ db.name }},cn=ldbm database,cn=plugins,cn=config {{ "(I: " + instance.name + ")" }}'
  community.general.ldap_attrs:
    bind_dn: '{{ dm_dn }}'
    bind_pw: '{{ dm_password }}'
    server_uri: '{{ server_uri }}'
    dn: 'cn=changelog,cn={{ db.name }},cn=ldbm database,cn=plugins,cn=config'
    attributes: '{{ instance.ldbm_database.changelog }}'
    state: exact
  when: instance.ldbm_database.changelog is defined

- name: 'Stop dirsrv service {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  ansible.builtin.service:
    name: 'dirsrv@{{ instance.name }}'
    state: stopped
  when: result.changed or result2.changed

- name: 'Calculate indices with dsctl db2index {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  ansible.builtin.command: '/usr/sbin/dsctl {{ instance.name }} db2index {{ db.name }}'
  args:
    chdir: /var/tmp
  when: result.changed or result2.changed

- name: 'Start dirsrv service {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  ansible.builtin.service:
    name: 'dirsrv@{{ instance.name }}'
    state: started
  when: result.changed or result2.changed


- name: 'Include VLV creation routine(s) {{ "(I: " + instance.name + ", S: " + suffix.name + ", DB: " + db.name + ")" }}'
  ansible.builtin.include_tasks: vlv.yml
  loop: '{{ db.vlv_index }}'
  loop_control:
    loop_var: vlv_index
  when: db.vlv_index is defined
  vars:
    vlv_prefix1: '{% if db.vlv_prefix is defined %}{{ db.vlv_prefix }}_{% endif %}'
    vlv_prefix2: '{% if db.vlv_prefix is defined %}{{ db.vlv_prefix }}.{% endif %}'
