---
# tasks file for rhds

- name: 'Install DS and dependencies'
  ansible.builtin.dnf:
    name:
      - "@redhat-ds:11"
      - cockpit-dashboard
    state: present

- name: 'Start Directory service on boot'
  ansible.builtin.service:
    name: 'dirsrv.target'
    enabled: true


- name: 'Include instance routines'
  ansible.builtin.include_tasks: instance.yml
  vars:
    dm_dn: '{{ instance.dm_dn | default(ds_app.dm_dn | default(ds_dm_dn)) }}'
    dm_password: '{{ instance.dm_password | default(ds_app.dm_password | default(ds_dm_password)) }}'
    port: '{{ instance.port | default(ds_app.port | default(ds_port)) }}'
    secure_port: '{{ instance.secure_port | default(ds_app.secure_port | default(ds_secure_port)) }}'
    replication_user: '{{ instance.replication_user | default(ds_app.replication_user | default(ds_replication_user)) }}'
    #server_uri: 'ldap://localhost:{{ instance.port }}'
    server_uri: 'ldapi://%2fvar%2frun%2fslapd-{{ instance.name }}.socket'
  loop: '{{ ds_app.instance }}'
  loop_control:
    loop_var: instance
