---
# tasks file for rhds

# An example of how to set distribution and version specific internal variables
# (defined in vars/ directory)
# see https://github.com/oasis-roles/meta_standards#platform-specific-variables
- name: "Set platform/version specific variables"
  ansible.builtin.include_vars: "{{ ds_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - >-
      {{ ansible_facts['distribution'] ~ '_' ~
      ansible_facts['distribution_major_version'] }}.yml
    - >-
      {{ ansible_facts['distribution'] ~ '_' ~
      ansible_facts['distribution_version'] }}.yml
  vars:
    ds_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: ds_vars_file is file
 
- name: 'Install DS and dependencies'
  ansible.builtin.package:
    name: "{{ ds_packages }}"
    state: present
 
- name: 'Start Directory service on boot'
  ansible.builtin.service:
    name: 'dirsrv.target'
    enabled: true

- name: 'Include instance routines'
  ansible.builtin.include_tasks: instance.yml
  vars:
    dm_dn: '{{ instance.dm_dn | default(ds_app.dm_dn | default(ds_dm_dn)) }}'
    dm_password: '{{ instance.dm_password | default(ds_app.dm_password | default(ds_dm_password)) }}'
    port: '{{ instance.port | default(ds_app.port | default(ds_port)) }}'
    secure_port: '{{ instance.secure_port | default(ds_app.secure_port | default(ds_secure_port)) }}'
    replication_user: '{{ instance.replication_user | default(ds_app.replication_user | default(ds_replication_user)) }}'
    #server_uri: 'ldap://localhost:{{ instance.port }}'
    server_uri: 'ldapi://%2fvar%2frun%2fslapd-{{ instance.name }}.socket'
  loop: '{{ ds_app.instance }}'
  loop_control:
    loop_var: instance
